[package]
name = "typestr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
itertools = { version = "0.12.1", default-features = false }
static_assertions = "1.1.0"

[features]
std = []
default = ["std"]
