[package]
name = "typeslice-macros"
version = "0.1.0"
edition = "2021"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.52", default-features = false, features = ["parsing", "printing", "proc-macro"] }
